### ISSUE TITLE
Bot Opportunies

### ISSUE THREAD

**Issue by guyjeangilles** [internetarchive/openlibrary-client#165]
### Preface
The old [Writing Bots Wiki](https://github.com/internetarchive/openlibrary/wiki/Writing-Bots) used to have a list of "Bot Opportunities" that have been migrated here. The list migrated from the wiki will likely need further breakdown.

Contributors can edit this issue to track all bot-related clean up
### Legend
   - A: Authors
   - E: Editions
   - W: Works

### Bot Clean up Opportunities
- [ ] Unicode [A, E, W]
  - 'mojibake' A~(c) style encoding errors. From multiple sources
      - Some from Amazon bulk imports
      - Some from external MARC records Some are lossy, others can be reconstructed. Important point to note: there are multiple styles that look similar, but require different translation to fix.
   - Combining diacritics. Some external MARC records have had subsequent correction, reimportation could catch many such cases internetarchive/openlibrary#150
   - NFC Normalisation. Of titles, description, place, i.e. all text fields. Ensure all input mechanisms normalise correctly. UI + import paths. TEST.
- [X] Spaces in OCAIDS [E] internetarchive/openlibrary#467
- [ ] URLs in OCAIDs [E]
   - not many?
- [ ] URLs in Amazon ids [E]
   - Needs checking. Some url ids appear to resolve correctly. Suspicion that some users are trying to insert affiliate links in OL ids. What is our policy on this? Should we be making more effort to ensure only Internet Archive affiliate links are used?
- [ ] Invalid ISBNs [E]
   - _10 and _13 Other ISBN fields; can they be used for anything?
      - repair if possible
      - normalise
      - remove if bad
      - test for reuse on multiple editions
- [ ] Invalid/Incorrect other ids [E, W]
   - [ ] LCCN internetarchive/openlibrary#2851 
   - [ ] OCLC
   - [ ] LibraryThing internetarchive/openlibrary#497 
   - Sometimes ids are valid but link to a different book. How to resolve?
- [ ] Empty Titles [A, E, W]
   - Repair if possible
   - Delete if junk data
- [ ] Titles varied only by punctuation or whitespace (where author is the same) [E, W]
   - Remove trailing ".", ":", ";"
   - Reduce whitespaces to single sp
   - When one version has a single sp and another has no sp, change latter to single sp (e.g. Hitchhiker's guide --> Hitch hiker's guide)
   - When one version has embedded punctuation and another does not, change latter to match former (e.g. Hitch hikers guide --> Hitch-hiker's guide)
- [ ] Name Order [A]
   - The Open Library convention is natural name order as opposed to "Last, First" Is everyone happy with this standard? How should titles be handled? e.g. Sir , Lord, Lady, Mrs. There seems to be variation in the data for this style of name.
   - Also, how to handle Aliases? I notice the author_role type https://openlibrary.org/type/author_role has an 'as' property. Is this to allow for name variations on a particular book?
- [ ] Bad Alternate names for authors [A] internetarchive/openlibrary#498 
- [ ] Orphaned Editions [E] internetarchive/openlibrary#153
- [ ] Works without Editions [W] internetarchive/openlibrary#2727
   - https://github.com/internetarchive/openlibrary/issues/44 Appears to be a merging task now. These editionless works look to be left over from moving editions (translations are a common example) to another work without converting the original work to a redirect. If there was some way to go back to the the original edition move and complete the work redirection? Perhaps the WorkBot log at https://github.com/internetarchive/openlibrary/blob/629f2afe8fbff9e8af50e00a57e756dff45a0d73/openlibrary/catalog/works/live.py#L438 might be helpful??
- [ ] Editions unlinked to Works [E]
   - Appears to occur mainly with apparently editionless works. How common is it? If rare, it should be fairly simple to address manually in librarian mode given a list of such editions.
- [ ] Authors without Work [A]
- [ ] Orphaned editions without Authors [A]
   - Where author is known to IA, from MARC records. Update the records from the original MARC. Many of the missing authors seem to be on books that have editors rather than straight authors. Is this a cause of the problem? How to correctly represent editors on Open Library works?
- [ ] Non-book Items internetarchive/openlibrary#2404

**Comment by LeadSongDog** [comment]
Another one: many author records have a trailing space in the name. These frequently are duplicates of records for the same author sans space. They should be corrected and, where appropriate, merged.

**Comment by DavosISJ** [comment]
I hav this for to help

import requests
import json
import time
import random
from datetime import datetime
import sys
import unicodedata
import re

# Corrección de compatibilidad para Python 3.10+
try:
    from collections.abc import Mapping
except ImportError:
    from collections import Mapping

class DavosSJWaybackBot:
    def __init__(self):
        self.version = "1.3 - Ultra Cleanup & Master Analysis"
        self.user_agent = "WaybackVolunteer_Global/1.3 (DavosSJ Studios; OpenLibrary-Bot-Fix)"
        self.db_logs = "preservation_master_log.json"
        self.platforms = ["Instagram", "Twitter", "Spotify", "OpenLibrary", "ArchiveOrg"]

    # --- MÓDULOS DE LIMPIEZA AVANZADA (Plan C - Bot Opportunities) ---

    def fix_unicode_mojibake(self, text):
        """Corrige mojibake y transcodificación de diacríticos combinados (\u0361)."""
        if not text: return text
        # Corrección específica para el error openlibrary#150 (\u0361)
        text = text.replace('\u0361', '') 
        try:
            return text.encode('latin-1').decode('utf-8')
        except (UnicodeEncodeError, UnicodeDecodeError):
            return unicodedata.normalize('NFC', text)

    def clean_ocaid(self, ocaid):
        """Limpia espacios (%20) y URLs en Internet Archive IDs (openlibrary#467)."""
        if not ocaid: return ocaid
        # Elimina espacios al final y posibles prefijos de URL
        ocaid = ocaid.strip().replace('%20', '')
        ocaid = re.sub(r'https?://archive\.org/details/', '', ocaid)
        return ocaid

    def validate_external_ids(self, id_type, value):
        """Valida LCCN, OCLC y IDs de Amazon para filtrar links de afiliados o basura."""
        if not value: return None
        if id_type == "LCCN":
            # Filtra LCCNs que contienen caracteres alfa incorrectos (#2851)
            return value if value.isdigit() else None
        if id_type == "AMAZON":
            # Detecta si intentan insertar links de afiliados
            if "tag=" in value or "http" in value:
                return None
        return value.strip()

    def advanced_title_normalization(self, title):
        """
        Normaliza títulos variados por puntuación o espacios.
        Ej: 'Hitchhiker\'s guide' -> 'Hitch-hiker\'s guide' (según estándar).
        """
        if not title: return title
        # 1. Reducir espacios múltiples
        title = " ".join(title.split())
        # 2. Remover puntuación trailing
        title = re.sub(r'[.:;,]\s*$', '', title)
        # 3. Normalización de guiones para consistencia (ejemplo de lógica de autor)
        # Aquí se podría expandir con un diccionario de variantes conocidas
        return title

    def filter_non_book_items(self, item_type, metadata):
        """Excluye DVDs y otros items no bibliográficos (openlibrary#2404)."""
        non_book_keywords = ['dvd', 'vhs', 'bluray', 'compact disc']
        content = str(metadata).lower()
        for key in non_book_keywords:
            if key in content:
                return False
        return True

    # --- LÓGICA DE INVESTIGACIÓN Y ARCHIVO ---

    def log_investigation(self, result):
        """Guarda los hallazgos en la base de datos de DavosSJ."""
        try:
            with open(self.db_logs, "a", encoding='utf-8') as f:
                f.write(json.dumps(result, ensure_ascii=False) + "\n")
        except Exception as e:
            print(f"Error en base de datos: {e}")

    def deep_analyze_profile(self, target):
        """Análisis maestro con protocolos de limpieza de Open Library."""
        platform = target['platform']
        handle = target['handle']
        
        # Simulación de datos extraídos con errores (Plan C)
        raw_data = {
            "title": "The Hitchhiker's Guide to the Galaxy. ",
            "ocaid": "hitchhikersguide00adam%20",
            "isbn": "0-330-25864-8",
            "lccn": "abc12345" # Inválido según #2851
        }
        
        # Procesamiento
        cleaned_title = self.advanced_title_normalization(raw_data['title'])
        valid_ocaid = self.clean_ocaid(raw_data['ocaid'])
        valid_lccn = self.validate_external_ids("LCCN", raw_data['lccn'])
        
        print(f"[@] Investigando: {handle} en {platform}")
        print(f"[*] Limpieza IA/OL: OCAID '{raw_data['ocaid']}' -> '{valid_ocaid}'")
        
        research_data = {
            "timestamp": datetime.now().isoformat(),
            "platform": platform,
            "profile_handle": handle,
            "cleaned_metadata": {
                "title": cleaned_title,
                "ocaid": valid_ocaid,
                "lccn_status": "Fixed" if not valid_lccn else "Valid",
                "is_book": self.filter_non_book_items("Edition", cleaned_title)
            },
            "archive_status": "Validated & Ready"
        }
        
        self.log_investigation(research_data)
        return research_data

    def start_global_mission(self, keywords):
        """Inicia la misión de limpieza y preservación global."""
        print(f"--- Sistema DavosSJ v{self.version} ---")
        print("[!] Aplicando Legend: A (Authors), E (Editions), W (Works)")
        for word in keywords:
            targets = [{"handle": f"{word}_vol", "platform": "OpenLibrary"}]
            for target in targets:
                self.deep_analyze_profile(target)
                time.sleep(0.3)

if __name__ == "__main__":
    investigator = DavosSJWaybackBot()
    busqueda_maestra = ["bot_cleanup", "metadata_repair"]
    investigator.start_global_mission(busqueda_maestra)
    print("\n[Misión Completada] El bot ha limpiado y preparado los datos para el archivo.")

**Comment by bitnapper** [comment]
I'd like to have a bot fixing some Unicode errors starting with the editions publishing place where München is imported as 'Mu nchen'.  Would that be an ok task to do?
